name: Release Drafter
on:
 pull_request:
 push:
   # branches to consider in the event; optional, defaults to all
   branches:
     - develop
jobs:
 update_release_draft:
   runs-on: ubuntu-latest
   steps:
     - uses: release-drafter/release-drafter@v5
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PREVIOUS_TAG: 1.0.1